# Generated by Django 5.0.6 on 2025-11-30 22:03

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
        ('projects', '0002_alter_project_options_project_default_language_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={'ordering': ['path', 'name']},
        ),
        migrations.AlterUniqueTogether(
            name='file',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='file',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_files', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='file',
            name='encoding',
            field=models.CharField(default='utf-8', max_length=20),
        ),
        migrations.AddField(
            model_name='file',
            name='path',
            field=models.CharField(blank=True, help_text='Full path including folder structure', max_length=1000),
        ),
        migrations.AddField(
            model_name='file',
            name='size',
            field=models.IntegerField(default=0, help_text='File size in bytes'),
        ),
        migrations.AddField(
            model_name='file',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_files', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='file',
            name='content',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='file',
            name='language',
            field=models.CharField(default='javascript', help_text='Programming language', max_length=50),
        ),
        migrations.AlterField(
            model_name='file',
            name='name',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='File name can only contain alphanumeric characters, spaces, dots, slashes, hyphens, and underscores.', regex='^[a-zA-Z0-9\\s\\.\\/\\-_]+$')]),
        ),
        migrations.AlterUniqueTogether(
            name='file',
            unique_together={('project', 'path', 'name')},
        ),
        migrations.AlterModelTable(
            name='file',
            table='file',
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='files.folder')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='projects.project')),
            ],
            options={
                'db_table': 'folder',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='file',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to='files.folder'),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['project', 'folder'], name='file_project_1e17cc_idx'),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['project', 'language'], name='file_project_47aaf3_idx'),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['project', '-updated_at'], name='file_project_6e88e3_idx'),
        ),
        migrations.AddIndex(
            model_name='folder',
            index=models.Index(fields=['project', 'parent'], name='folder_project_9dd7a1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='folder',
            unique_together={('project', 'parent', 'name')},
        ),
    ]
